---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

name: 'GitHub Actions Lint'

# yamllint disable-line rule:truthy
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  lint:
    name: 'Lint GitHub Actions'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      # Load the LF Release Engineering egress allow-list before
      # harden-runner enables block mode.
      - name: 'Load egress allow-list'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/harden-runner-block-action@805eedb0508c07714b61887a2b87a5c4bbeff22a  # v0.12.1
        with:
          # yamllint disable-line rule:line-length
          config: 'lfreleng-actions/.github//.github/harden-runner/lfreleng-actions/allow_list.txt@18d9c4446bea555d0783e850f6d295f844fe8f67'

      - name: 'Harden runner'
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1  # v2.21.1
        with:
          egress-policy: 'block'
          allowed-endpoints: >
            ${{ env.CONNECTION_ALLOW_LIST }}

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: 'Run LF pre-commit checks'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/standalone-linting-action@7ad4dc56cdf2600bd792eaa561e56529fa9a85e8  # v0.4.2
        with:
          no_checkout: 'true'
          github_token: ${{ github.token }}
