---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

name: 'GitHub Actions Lint'

# yamllint disable-line rule:truthy
on:
  pull_request:

permissions: {}

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  lint:
    name: 'Lint GitHub Actions'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: 'Harden runner'
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40  # v2.20.1
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: 'Lint GitHub workflows and actions'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/gha-workflow-linter@1deeb31e2474a7610a1a1bc2094d829ef637d09b  # v1.5.5
        with:
          auto-fix: false
          require-pinned-sha: true
          skip-actions: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
