---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

name: 'GitHub Actions Lint'

# yamllint disable-line rule:truthy
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  lint:
    name: 'Lint GitHub Actions'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: 'Harden runner'
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c  # v2.21.0
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: 'Run LF pre-commit checks'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/standalone-linting-action@274940345e6674c5af91bcb61735be24018c27a3  # v0.4.0
        with:
          no_checkout: 'true'
          github_token: ${{ github.token }}
