---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

name: 'Test Otterdog Validate'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: 'Test Otterdog Validate'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5

    steps:
      - name: 'Harden runner'
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c  # v2.21.0
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: 'Install Otterdog'
        uses: ./.github/actions/install-otterdog

      - name: 'Validate Otterdog configuration'
        uses: ./.github/actions/otterdog-validate
        with:
          organization: 'lfit-otterdoc-poc'
        env:
          OTTER_API_TOKEN: ${{ secrets.OTTER_API_TOKEN }}
